# Generated by Django 4.2 on 2023-07-15 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Health_Record',
            fields=[
                ('recordNum', models.CharField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Medical_History',
            fields=[
                ('histNum', models.AutoField(primary_key=True, serialize=False)),
                ('health_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.health_record')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('drugId', models.CharField(primary_key=True, serialize=False)),
                ('drugCode', models.CharField()),
                ('drugName', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('middleName', models.CharField(blank=True, max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')])),
                ('birthDate', models.DateField()),
                ('registration', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('sympNum', models.AutoField(primary_key=True, serialize=False)),
                ('symptom', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('presNum', models.AutoField(primary_key=True, serialize=False)),
                ('dosage', models.PositiveIntegerField()),
                ('timeFrame', models.DateTimeField()),
                ('amount', models.PositiveIntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('health_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.health_record')),
            ],
        ),
        migrations.CreateModel(
            name='Prescribed_Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Symptom',
            fields=[
                ('sympID', models.AutoField(primary_key=True, serialize=False)),
                ('medical_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medical_history')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.symptom')),
            ],
        ),
        migrations.AddField(
            model_name='health_record',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comNum', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=3000)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('health_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.health_record')),
            ],
        ),
    ]
