# Generated by Django 5.0.1 on 2024-04-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='department',
            field=models.CharField(choices=[('Junior HS', 'Junior HS'), ('SOL', 'SOL'), ('SED', 'SED'), ('Kindergarten', 'Kindergarten'), ('SBM', 'SBM'), ('SOE', 'SOE'), ('SAMS', 'SAMS'), ('SAS', 'SAS'), ('Nursery', 'Nursery'), ('Senior HS', 'Senior HS'), ('SCS', 'SCS')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientStatus',
            field=models.CharField(choices=[('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Single', 'Single'), ('Married', 'Married'), ('Separated', 'Separated')]),
        ),
    ]
