# Generated by Django 5.0.1 on 2024-02-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='present_illness',
            old_name='assignedPhysician',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientStatus',
            field=models.CharField(choices=[('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Single', 'Single'), ('Separated', 'Separated')]),
        ),
    ]
