# Generated by Django 5.0.1 on 2024-04-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='department',
            field=models.CharField(choices=[('Junior HS', 'Junior HS'), ('SCS', 'SCS'), ('SAMS', 'SAMS'), ('SED', 'SED'), ('SOL', 'SOL'), ('SOE', 'SOE'), ('Kindergarten', 'Kindergarten'), ('Senior HS', 'Senior HS'), ('SBM', 'SBM'), ('SAS', 'SAS'), ('Nursery', 'Nursery')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientStatus',
            field=models.CharField(choices=[('Single', 'Single'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Married', 'Married'), ('Divorced', 'Divorced')]),
        ),
    ]
