# Generated by Django 5.0.1 on 2024-02-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patientStatus',
            field=models.CharField(choices=[('Single', 'Single'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Married', 'Married'), ('Separated', 'Separated')]),
        ),
        migrations.AlterField(
            model_name='present_illness',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
