# Generated by Django 4.2.3 on 2024-01-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='department',
        ),
        migrations.AlterField(
            model_name='patient',
            name='course',
            field=models.CharField(choices=[('Kindergarten', 'Kindergarten'), ('Law School', 'Law School'), ('Tertiary', 'Tertiary'), ('Senior High School', 'Senior High School'), ('Junior High School', 'Junior High School'), ('Nursery', 'Nursery')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='middleInitial',
            field=models.CharField(max_length=1),
        ),
    ]
