# Generated by Django 4.2.3 on 2023-11-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='user',
            field=models.CharField(blank=True, null=True),
        ),
    ]
