<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-01-27 15:26
=======
# Generated by Django 4.2.3 on 2024-01-27 11:54
>>>>>>> frontend-fixes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientStatus',
<<<<<<< HEAD
            field=models.CharField(choices=[('Married', 'Married'), ('Separated', 'Separated'), ('Widowed', 'Widowed'), ('Single', 'Single'), ('Divorced', 'Divorced')]),
=======
            field=models.CharField(choices=[('Single', 'Single'), ('Divorced', 'Divorced'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated')]),
>>>>>>> frontend-fixes
        ),
    ]
