# Generated by Django 4.2 on 2023-07-10 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_History',
            fields=[
                ('histNum', models.AutoField(primary_key=True, serialize=False)),
                ('health_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.health_record')),
            ],
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('sympNum', models.AutoField(primary_key=True, serialize=False)),
                ('symptom', models.CharField(max_length=3000)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')]),
        ),
        migrations.CreateModel(
            name='Prescribed_Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Symptoms',
            fields=[
                ('sympID', models.AutoField(primary_key=True, serialize=False)),
                ('medical_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medical_history')),
            ],
        ),
    ]
