# Generated by Django 5.0.1 on 2024-01-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical_record',
            old_name='pastDisease',
            new_name='pastDiseases',
        ),
        migrations.AlterField(
            model_name='patient',
            name='course',
            field=models.CharField(choices=[('Junior High School', 'Junior High School'), ('Tertiary', 'Tertiary'), ('Kindergarten', 'Kindergarten'), ('Law School', 'Law School'), ('Senior High School', 'Senior High School'), ('Nursery', 'Nursery')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')]),
        ),
    ]
