# Generated by Django 5.0.1 on 2024-03-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='illnessID',
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientStatus',
            field=models.CharField(choices=[('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Single', 'Single'), ('Separated', 'Separated'), ('Married', 'Married')]),
        ),
    ]
