# Generated by Django 4.2 on 2023-07-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_medical_history_symptoms_alter_patient_gender_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data_Logs',
            new_name='Data_Log',
        ),
        migrations.RenameModel(
            old_name='Patient_Symptoms',
            new_name='Patient_Symptom',
        ),
        migrations.RenameModel(
            old_name='Personal_Notes',
            new_name='Personal_Note',
        ),
        migrations.RenameModel(
            old_name='Symptoms',
            new_name='Symptom',
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')]),
        ),
    ]
