# Generated by Django 5.0.1 on 2024-04-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_course_patient_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='department',
            field=models.CharField(choices=[('SAS', 'SAS'), ('Kindergarten', 'Kindergarten'), ('Senior High School', 'Senior High School'), ('SCS', 'SCS'), ('Junior High School', 'Junior High School'), ('SOL', 'SOL'), ('SED', 'SED'), ('Nursery', 'Nursery'), ('SBM', 'SBM'), ('SAMS', 'SAMS'), ('SOE', 'SOE')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientStatus',
            field=models.CharField(choices=[('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Married', 'Married'), ('Single', 'Single')]),
        ),
    ]
