# Generated by Django 5.0.1 on 2024-04-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_medical_record_lastmensperiod_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='presNum',
            new_name='presID',
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientStatus',
            field=models.CharField(choices=[('Separated', 'Separated'), ('Married', 'Married'), ('Single', 'Single'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')]),
        ),
    ]
