# Generated by Django 5.0.1 on 2024-01-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_patient_department_alter_patient_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='course',
            field=models.CharField(choices=[('Kindergarten', 'Kindergarten'), ('Tertiary', 'Tertiary'), ('Law School', 'Law School'), ('Senior High School', 'Senior High School'), ('Junior High School', 'Junior High School'), ('Nursery', 'Nursery')]),
        ),
    ]
