# Generated by Django 5.0.1 on 2024-03-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_prescription_illnessid_alter_patient_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientStatus',
            field=models.CharField(choices=[('Single', 'Single'), ('Separated', 'Separated'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Married', 'Married')]),
        ),
    ]
