# Generated by Django 4.2.3 on 2024-01-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_health_record_symptoms_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health_record',
            name='diseases',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')]),
        ),
    ]
