# Generated by Django 5.0.1 on 2024-01-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_pastdisease_medical_record_pastdiseases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='course',
            field=models.CharField(choices=[('Junior High School', 'Junior High School'), ('Senior High School', 'Senior High School'), ('Tertiary', 'Tertiary'), ('Nursery', 'Nursery'), ('Law School', 'Law School'), ('Kindergarten', 'Kindergarten')]),
        ),
    ]
