# Generated by Django 5.0.1 on 2024-04-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_patient_department_alter_patient_patientstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='department',
            field=models.CharField(choices=[('Nursery', 'Nursery'), ('SCS', 'SCS'), ('SAMS', 'SAMS'), ('SAS', 'SAS'), ('SOE', 'SOE'), ('Junior HS', 'Junior HS'), ('Senior HS', 'Senior HS'), ('Kindergarten', 'Kindergarten'), ('SOL', 'SOL'), ('SED', 'SED'), ('SBM', 'SBM')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientStatus',
            field=models.CharField(choices=[('Single', 'Single'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Divorced', 'Divorced'), ('Married', 'Married')]),
        ),
    ]
