# Generated by Django 5.0.1 on 2024-02-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_patient_account_alter_patient_patientstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patientStatus',
            field=models.CharField(choices=[('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Divorced', 'Divorced'), ('Single', 'Single'), ('Married', 'Married')]),
        ),
    ]
