# Generated by Django 4.2.3 on 2024-01-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_health_record_diseases_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health_record',
            name='allergies',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='health_record',
            name='familyHistory',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='health_record',
            name='illnesses',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='health_record',
            name='pastDisease',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
