# Generated by Django 5.0.1 on 2024-04-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_patient_department_alter_patient_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='department',
            field=models.CharField(choices=[('SAS', 'SAS'), ('Nursery', 'Nursery'), ('SOL', 'SOL'), ('Junior HS', 'Junior HS'), ('SCS', 'SCS'), ('Kindergarten', 'Kindergarten'), ('Senior HS', 'Senior HS'), ('SBM', 'SBM'), ('SED', 'SED'), ('SAMS', 'SAMS'), ('SOE', 'SOE')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientStatus',
            field=models.CharField(choices=[('Single', 'Single'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Married', 'Married'), ('Separated', 'Separated')]),
        ),
    ]
