# Generated by Django 5.0.1 on 2024-01-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_patient_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='course',
            field=models.CharField(choices=[('Nursery', 'Nursery'), ('Tertiary', 'Tertiary'), ('Kindergarten', 'Kindergarten'), ('Junior High School', 'Junior High School'), ('Senior High School', 'Senior High School'), ('Law School', 'Law School')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
