# Generated by Django 4.2.1 on 2023-07-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_labresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labresult',
            name='pdf',
            field=models.FileField(upload_to='upload/'),
        ),
    ]
