# Generated by Django 5.0.1 on 2024-01-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_contactid_contact_person_contactid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='present_illness',
            name='illnessName',
            field=models.CharField(default='illnessName', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientStatus',
            field=models.CharField(choices=[('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Divorced', 'Divorced'), ('Single', 'Single'), ('Married', 'Married')]),
        ),
    ]
