# Generated by Django 5.0.1 on 2024-01-18 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_patient_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='assignedPhysician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='course',
            field=models.CharField(choices=[('Nursery', 'Nursery'), ('Kindergarten', 'Kindergarten'), ('Junior High School', 'Junior High School'), ('Tertiary', 'Tertiary'), ('Law School', 'Law School'), ('Senior High School', 'Senior High School')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')]),
        ),
        migrations.CreateModel(
            name='Present_Illness',
            fields=[
                ('illnessNum', models.AutoField(primary_key=True, serialize=False)),
                ('complaint', models.TextField(default=None)),
                ('findings', models.TextField(default=None)),
                ('diagnosis', models.TextField(default=None)),
                ('treatment', models.TextField(default=None)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
    ]
