# Generated by Django 5.0.1 on 2024-04-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_patient_department_alter_patient_patientstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='department',
            field=models.CharField(choices=[('Nursery', 'Nursery'), ('Junior High School', 'Junior High School'), ('SCS', 'SCS'), ('SOL', 'SOL'), ('SED', 'SED'), ('Kindergarten', 'Kindergarten'), ('SOE', 'SOE'), ('SAMS', 'SAMS'), ('Senior High School', 'Senior High School'), ('SAS', 'SAS'), ('SBM', 'SBM')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientStatus',
            field=models.CharField(choices=[('Single', 'Single'), ('Widowed', 'Widowed'), ('Married', 'Married'), ('Separated', 'Separated'), ('Divorced', 'Divorced')]),
        ),
    ]
