# Generated by Django 5.0.1 on 2024-01-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_patient_course_alter_patient_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='course',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')]),
        ),
    ]
