# Generated by Django 5.0.1 on 2024-02-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_patient_patientstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='account',
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientStatus',
            field=models.CharField(choices=[('Single', 'Single'), ('Divorced', 'Divorced'), ('Married', 'Married'), ('Separated', 'Separated'), ('Widowed', 'Widowed')]),
        ),
    ]
