# Generated by Django 4.2.1 on 2023-07-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_labresult_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdfJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='labresult',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
