# Generated by Django 5.0.1 on 2024-02-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_patient_patientstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientStatus',
            field=models.CharField(choices=[('Divorced', 'Divorced'), ('Single', 'Single'), ('Separated', 'Separated'), ('Married', 'Married'), ('Widowed', 'Widowed')]),
        ),
        migrations.AlterField(
            model_name='present_illness',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
