# Generated by Django 5.0.1 on 2024-01-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_patient_assignedphysician_alter_patient_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='course',
            field=models.CharField(choices=[('Kindergarten', 'Kindergarten'), ('Senior High School', 'Senior High School'), ('Nursery', 'Nursery'), ('Junior High School', 'Junior High School'), ('Law School', 'Law School'), ('Tertiary', 'Tertiary')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientID',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
