# Generated by Django 4.2.3 on 2023-07-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_csvdrug_drugmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drugmodel',
            options={'ordering': ['bnf']},
        ),
        migrations.RemoveField(
            model_name='drugmodel',
            name='drugID',
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')]),
        ),
    ]
