# Generated by Django 4.2.3 on 2023-07-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_patient_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bnf', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=128)),
                ('csv', models.FileField(upload_to='csv/')),
            ],
            options={
                'ordering': ['bnf'],
            },
        ),
        migrations.DeleteModel(
            name='CSVDrug',
        ),
        migrations.DeleteModel(
            name='DrugModel',
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')]),
        ),
    ]
