# Generated by Django 5.0.1 on 2024-01-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_patient_course_alter_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patientStatus',
            field=models.CharField(choices=[('Separated', 'Separated'), ('Married', 'Married'), ('Single', 'Single'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced')], default='Married'),
            preserve_default=False,
        ),
    ]
