# Generated by Django 4.2.3 on 2023-07-12 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_drugmodel_options_remove_drugmodel_drugid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_symptom',
            name='symptom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.symptom'),
            preserve_default=False,
        ),
    ]
