# Generated by Django 5.0.1 on 2024-02-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_patient_gender_alter_patient_patientstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientStatus',
            field=models.CharField(choices=[('Married', 'Married'), ('Widowed', 'Widowed'), ('Single', 'Single'), ('Separated', 'Separated'), ('Divorced', 'Divorced')]),
        ),
        migrations.AlterField(
            model_name='present_illness',
            name='created_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='present_illness',
            name='updated_at',
            field=models.DateField(null=True),
        ),
    ]
