# Generated by Django 4.2.3 on 2023-07-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_csvfile_delete_csvdrug_delete_drugmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='csv',
            field=models.FileField(blank=True, upload_to='csv/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')]),
        ),
    ]
