# Generated by Django 5.0.1 on 2024-02-04 16:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_patient_gender_alter_patient_patientstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patientStatus',
            field=models.CharField(choices=[('Single', 'Single'), ('Separated', 'Separated'), ('Divorced', 'Divorced'), ('Married', 'Married'), ('Widowed', 'Widowed')]),
        ),
        migrations.AlterField(
            model_name='present_illness',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='present_illness',
            name='updated_at',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
