# Generated by Django 4.2.3 on 2023-07-22 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_csvfile_csv_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvfile',
            options={'ordering': ['csv']},
        ),
        migrations.RemoveField(
            model_name='csvfile',
            name='bnf',
        ),
        migrations.RemoveField(
            model_name='csvfile',
            name='description',
        ),
    ]
