# Generated by Django 4.2.3 on 2023-07-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_csvfile_options_remove_csvfile_bnf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulk_Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bnf', models.CharField(blank=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'ordering': ['bnf'],
            },
        ),
        migrations.RenameModel(
            old_name='CSVFile',
            new_name='Csv_Upload',
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')]),
        ),
    ]
