# Generated by Django 5.0.1 on 2024-02-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_patient_gender_alter_patient_patientstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patientStatus',
            field=models.CharField(choices=[('Divorced', 'Divorced'), ('Single', 'Single'), ('Separated', 'Separated'), ('Widowed', 'Widowed'), ('Married', 'Married')]),
        ),
        migrations.AlterField(
            model_name='present_illness',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='present_illness',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
