# Generated by Django 4.2.3 on 2023-07-23 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulk_drug',
            options={'ordering': ['csv']},
        ),
        migrations.RemoveField(
            model_name='bulk_drug',
            name='bnf',
        ),
        migrations.RemoveField(
            model_name='bulk_drug',
            name='description',
        ),
        migrations.AddField(
            model_name='bulk_drug',
            name='csv',
            field=models.FileField(default=django.utils.timezone.now, upload_to='csv/'),
            preserve_default=False,
        ),
    ]
