# Generated by Django 5.0.1 on 2024-02-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_patient_patientstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientStatus',
            field=models.CharField(choices=[('Separated', 'Separated'), ('Single', 'Single'), ('Widowed', 'Widowed'), ('Married', 'Married'), ('Divorced', 'Divorced')]),
        ),
        migrations.AlterField(
            model_name='present_illness',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='present_illness',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
