# Generated by Django 4.2.3 on 2023-07-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_bulk_drug_options_bulk_drug_bnf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulk_drug',
            name='csv',
        ),
        migrations.AlterField(
            model_name='bulk_drug',
            name='bnf',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bulk_drug',
            name='description',
            field=models.CharField(max_length=128),
        ),
    ]
