# Generated by Django 5.0.1 on 2024-02-04 17:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_patient_gender_alter_patient_patientstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientStatus',
            field=models.CharField(choices=[('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Married', 'Married'), ('Single', 'Single'), ('Separated', 'Separated')]),
        ),
        migrations.AlterField(
            model_name='present_illness',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='present_illness',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
