# Generated by Django 4.2.3 on 2023-07-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_upload',
            name='csv',
            field=models.FileField(upload_to='csv/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')]),
        ),
    ]
