# Generated by Django 4.2.3 on 2023-07-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulk_drug',
            name='csv',
            field=models.FileField(blank=True, upload_to='csv/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')]),
        ),
    ]
