# Generated by Django 4.2.3 on 2023-07-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_bulk_drug_csv_alter_patient_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulk_drug',
            name='csv',
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')]),
        ),
    ]
