# Generated by Django 4.2.3 on 2023-07-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_patient_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bulk_Drug',
            new_name='Mims',
        ),
        migrations.DeleteModel(
            name='Csv_Upload',
        ),
    ]
