# Generated by Django 4.2.3 on 2023-07-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_patient_gender'),
        ('api', '0023_rename_bulk_drug_mims_delete_csv_upload'),
    ]

    operations = [
    ]
