# Generated by Django 4.2.3 on 2023-07-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_patient_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mims',
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')]),
        ),
    ]
