# Generated by Django 4.2.3 on 2023-08-01 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_delete_mims_alter_patient_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('pdfId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('comment', models.TextField(max_length=512)),
                ('pdf', models.FileField(upload_to='upload-pdf/')),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')]),
        ),
        migrations.CreateModel(
            name='JsonLabResult',
            fields=[
                ('jsonId', models.AutoField(primary_key=True, serialize=False)),
                ('jsonData', models.JSONField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('labresult', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.labresult')),
            ],
        ),
    ]
