# Generated by Django 4.2.3 on 2023-08-06 00:19

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_patient_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('pdfId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('comment', models.TextField(max_length=512)),
                ('pdf', models.FileField(upload_to='upload-pdf/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='JsonLabResult',
            fields=[
                ('jsonId', models.AutoField(primary_key=True, serialize=False)),
                ('jsonData', models.JSONField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128)),
                ('comment', models.TextField(max_length=512)),
                ('labresult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.labresult')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
    ]
