# Generated by Django 4.2.3 on 2023-08-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_patient_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonLabResult',
            fields=[
                ('jsonId', models.AutoField(primary_key=True, serialize=False)),
                ('jsonData', models.JSONField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('pdfId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('comment', models.TextField(max_length=512)),
                ('pdf', models.FileField(upload_to='upload-pdf/')),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')]),
        ),
    ]
