# Generated by Django 4.2.3 on 2023-08-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_labresult_jsonlabresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_symptom',
            name='medical_history',
        ),
        migrations.RemoveField(
            model_name='patient_symptom',
            name='symptom',
        ),
        migrations.RemoveField(
            model_name='prescribed_medicine',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='prescribed_medicine',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='timeFrame',
        ),
        migrations.AddField(
            model_name='health_record',
            name='diseases',
            field=models.JSONField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='health_record',
            name='symptoms',
            field=models.JSONField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicines',
            field=models.JSONField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')]),
        ),
        migrations.DeleteModel(
            name='Medical_History',
        ),
        migrations.DeleteModel(
            name='Patient_Symptom',
        ),
        migrations.DeleteModel(
            name='Prescribed_Medicine',
        ),
        migrations.DeleteModel(
            name='Symptom',
        ),
    ]
