# Generated by Django 4.2.3 on 2023-08-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_patient_symptom_medical_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health_record',
            name='recordNum',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')]),
        ),
    ]
