# Generated by Django 4.2.3 on 2023-07-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_patient_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('pdfId', models.CharField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('comment', models.TextField(max_length=512)),
            ],
        ),
    ]
