# Generated by Django 4.2.3 on 2023-08-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.CharField(blank=True, null=True),
        ),
    ]
