# Generated by Django 4.2.3 on 2023-07-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_labresult_pdf_alter_patient_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonLabResult',
            fields=[
                ('jsonId', models.AutoField(primary_key=True, serialize=False)),
                ('jsonData', models.JSONField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')]),
        ),
    ]
