# Generated by Django 4.2.3 on 2023-07-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_account_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_note',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personal_note',
            name='noteNum',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
