# Generated by Django 4.2.3 on 2024-01-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_account_options_alter_data_log_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
