# Generated by Django 5.0.1 on 2024-02-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_account_accountid'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='suffixTitle',
            field=models.CharField(default='M.D.', max_length=10),
            preserve_default=False,
        ),
    ]
