# Generated by Django 5.0.1 on 2024-02-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_account_suffixtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='data_log',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personal_note',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
