# Generated by Django 4.2.3 on 2023-07-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_data_log_type_personal_note_user_alter_data_log_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_log',
            name='type',
            field=models.CharField(max_length=1000),
        ),
    ]
