# Generated by Django 4.2.3 on 2023-10-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_data_log_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_photo',
            field=models.ImageField(blank=True, default=None, upload_to='upload-photo/'),
        ),
    ]
