# Generated by Django 5.0.1 on 2024-04-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_account_accountrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountRole',
            field=models.CharField(blank=True, choices=[('physician', 'Physician'), ('nurse', 'Nurse'), ('working student', 'Working Student'), ('admin', 'Admin')], max_length=100),
        ),
    ]
